#lang racket
(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define failure-count 0)
  (define (dispatch pwd m)
    (if (eq? pwd password)
        (begin (set! failure-count 0)
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unknown request -- MAKE-ACCOUNT"
                                  m))))
        (begin (set! failure-count (+ failure-count 1))
               (when (>= failure-count 7)
                 (call-the-cops))
               (error "Incorrect password"))))
  dispatch)

(define (call-the-cops)
  (error "ACCOUNT POTENTIALLY COMPROMISED"))